version: '3.3'
services:

  database:
    image: "postgres"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist db data
    ports:
      - "5432:5432"
    env_file:
      - database.env

volumes:
  database-data:
